/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import type { IDisposable } from "@fluidframework/core-interfaces";
import {
	IChannel,
	IChannelAttributes,
	IChannelFactory,
	IFluidDataStoreRuntime,
} from "@fluidframework/datastore-definitions/internal";
import {
	IDocumentStorageService,
	ISnapshotTree,
} from "@fluidframework/driver-definitions/internal";
import { readAndParse } from "@fluidframework/driver-utils/internal";
import {
	IExperimentalIncrementalSummaryContext,
	ISummaryTreeWithStats,
	ITelemetryContext,
	IGarbageCollectionData,
	IFluidDataStoreContext,
	ISummarizeResult,
	type IRuntimeMessageCollection,
} from "@fluidframework/runtime-definitions/internal";
import { addBlobToSummary } from "@fluidframework/runtime-utils/internal";
import {
	ITelemetryLoggerExt,
	DataCorruptionError,
	tagCodeArtifacts,
} from "@fluidframework/telemetry-utils/internal";

import { ChannelDeltaConnection } from "./channelDeltaConnection.js";
import { ChannelStorageService } from "./channelStorageService.js";
import { ISharedObjectRegistry } from "./dataStoreRuntime.js";

export const attributesBlobKey = ".attributes";

export interface IChannelContext {
	getChannel(): Promise<IChannel>;

	setConnectionState(connected: boolean, clientId?: string);

	/**
	 * Process messages for this channel context. The messages here are contiguous messages for this context in a batch.
	 * @param messageCollection - The collection of messages to process.
	 */
	processMessages(messageCollection: IRuntimeMessageCollection): void;

	summarize(
		fullTree?: boolean,
		trackState?: boolean,
		telemetryContext?: ITelemetryContext,
	): Promise<ISummarizeResult>;

	reSubmit(content: any, localOpMetadata: unknown): void;

	applyStashedOp(content: any): unknown;

	rollback(message: any, localOpMetadata: unknown): void;

	/**
	 * Returns the data used for garbage collection. This includes a list of GC nodes that represent this context
	 * including any of its children. Each node has a set of outbound routes to other GC nodes in the document.
	 * @param fullGC - true to bypass optimizations and force full generation of GC data.
	 */
	getGCData(fullGC?: boolean): Promise<IGarbageCollectionData>;

	/**
	 * After GC has run, called to notify this context of routes that are used in it. These are used for the following:
	 * 1. To identify if this context is being referenced in the document or not.
	 * 2. To identify if this context or any of its children's used routes changed since last summary.
	 * 3. They are added to the summary generated by this context.
	 */
	updateUsedRoutes(usedRoutes: string[]): void;

	branchChannel<T extends IChannel>(branchPendingManager?: BranchPendingManager): Promise<T>;
}

export interface ChannelServiceEndpoints extends IDisposable {
	deltaConnection: ChannelDeltaConnection;
	objectStorage: ChannelStorageService;
}

export function toChannelServiceEndpoints(
	deltaConnection: ChannelDeltaConnection,
	objectStorage: ChannelStorageService,
) {
	return {
		deltaConnection,
		objectStorage,
		dispose: (e) => deltaConnection.dispose(e),
		get disposed() {
			return deltaConnection.disposed;
		},
	};
}

export function createChannelServiceEndpoints(
	connected: boolean,
	submitFn: (content: any, localOpMetadata: unknown) => void,
	dirtyFn: () => void,
	isAttachedAndVisible: () => boolean,
	storageService: IDocumentStorageService,
	logger: ITelemetryLoggerExt,
	tree?: ISnapshotTree,
	extraBlobs?: Map<string, ArrayBufferLike>,
): ChannelServiceEndpoints {
	const deltaConnection = new ChannelDeltaConnection(
		connected,
		(message, localOpMetadata) => submitFn(message, localOpMetadata),
		dirtyFn,
		isAttachedAndVisible,
	);
	const objectStorage = new ChannelStorageService(tree, storageService, logger, extraBlobs);

	return toChannelServiceEndpoints(deltaConnection, objectStorage);
}

/** Used to get the channel's summary for the DDS or DataStore attach op */
export function summarizeChannel(
	channel: IChannel,
	fullTree: boolean = false,
	trackState: boolean = false,
	telemetryContext?: ITelemetryContext,
): ISummaryTreeWithStats {
	const summarizeResult = channel.getAttachSummary(fullTree, trackState, telemetryContext);

	// Add the channel attributes to the returned result.
	addBlobToSummary(summarizeResult, attributesBlobKey, JSON.stringify(channel.attributes));
	return summarizeResult;
}

export async function summarizeChannelAsync(
	channel: IChannel,
	fullTree: boolean = false,
	trackState: boolean = false,
	telemetryContext?: ITelemetryContext,
	incrementalSummaryContext?: IExperimentalIncrementalSummaryContext,
): Promise<ISummaryTreeWithStats> {
	const summarizeResult = await channel.summarize(
		fullTree,
		trackState,
		telemetryContext,
		incrementalSummaryContext,
	);

	// Add the channel attributes to the returned result.
	addBlobToSummary(summarizeResult, attributesBlobKey, JSON.stringify(channel.attributes));
	return summarizeResult;
}

export async function loadChannelFactoryAndAttributes(
	dataStoreContext: IFluidDataStoreContext,
	services: ChannelServiceEndpoints,
	channelId: string,
	registry: ISharedObjectRegistry,
	attachMessageType?: string,
): Promise<{ factory: IChannelFactory; attributes: IChannelAttributes }> {
	let attributes: IChannelAttributes | undefined;
	if (await services.objectStorage.contains(attributesBlobKey)) {
		attributes = await readAndParse<IChannelAttributes | undefined>(
			services.objectStorage,
			attributesBlobKey,
		);
	}

	// This is a backward compatibility case where the attach message doesn't include attributes. They must
	// include attach message type.
	// Since old attach messages will not have attributes, we need to keep this as long as we support old attach
	// messages.
	const channelFactoryType = attributes ? attributes.type : attachMessageType;
	if (channelFactoryType === undefined) {
		throw new DataCorruptionError(
			"channelTypeNotAvailable",
			tagCodeArtifacts({
				channelId,
				dataStoreId: dataStoreContext.id,
				dataStorePackagePath: dataStoreContext.packagePath.join("/"),
				channelFactoryType,
			}),
		);
	}
	const factory = registry.get(channelFactoryType);
	if (factory === undefined) {
		throw new DataCorruptionError(
			"channelFactoryNotRegisteredForGivenType",
			tagCodeArtifacts({
				channelId,
				dataStoreId: dataStoreContext.id,
				dataStorePackagePath: dataStoreContext.packagePath.join("/"),
				channelFactoryType,
			}),
		);
	}
	// This is a backward compatibility case where the attach message doesn't include attributes. Get the attributes
	// from the factory.
	attributes = attributes ?? factory.attributes;
	return { factory, attributes };
}

export async function loadChannel(
	dataStoreRuntime: IFluidDataStoreRuntime,
	attributes: IChannelAttributes,
	factory: IChannelFactory,
	services: ChannelServiceEndpoints,
	logger: ITelemetryLoggerExt,
	channelId: string,
): Promise<IChannel> {
	// Compare snapshot version to collaborative object version
	if (
		attributes.snapshotFormatVersion !== undefined &&
		attributes.snapshotFormatVersion !== factory.attributes.snapshotFormatVersion
	) {
		logger.sendTelemetryEvent({
			eventName: "ChannelAttributesVersionMismatch",
			...tagCodeArtifacts({
				channelType: attributes.type,
				channelSnapshotVersion: `${attributes.snapshotFormatVersion}@${attributes.packageVersion}`,
				channelCodeVersion: `${factory.attributes.snapshotFormatVersion}@${factory.attributes.packageVersion}`,
			}),
		});
	}

	return factory.load(dataStoreRuntime, channelId, services, attributes);
}

export async function branchChannel<T extends IChannel>({
	mainChannel,
	channelServices,
	dataStoreRuntime,
	factory,
	logger,
	branchPendingManager,
}: {
	mainChannel: T;
	channelServices: ChannelServiceEndpoints;
	dataStoreRuntime: IFluidDataStoreRuntime;
	factory: IChannelFactory;
	logger: ITelemetryLoggerExt;
	branchPendingManager?: BranchPendingManager;
}): Promise<{ channel: T; services: ChannelServiceEndpoints }> {
	const services: ChannelServiceEndpoints = toChannelServiceEndpoints(
		ChannelDeltaConnection.clone(channelServices.deltaConnection, {
			submit: () => {
				if (services.disposed) {
					throw new Error("disposed");
				}
			},
			dirty: () => {},
		}),
		channelServices.objectStorage,
	);

	const channel = (await loadChannel(
		dataStoreRuntime,
		mainChannel.attributes,
		factory,
		services,
		logger,
		mainChannel.id,
	)) as T;

	const pendingManger = branchPendingManager ?? new BranchPendingManager();
	pendingManger.register(channelServices.deltaConnection, services.deltaConnection);

	return { channel, services };
}

export class BranchPendingManager implements IDisposable {
	disposed: boolean = false;
	dispose(error?: Error): void {
		if (!this.disposed) {
			this.disposed = true;
			for (const change of this.branchPending.splice(0)) {
				change.branchDelta.dispose(error);
			}
		}
	}
	private readonly branchPending: {
		content: unknown;
		branchMetadata: unknown;
		branchDelta: ChannelDeltaConnection;
		channelDelta: ChannelDeltaConnection;
	}[] = [];

	register(channelDelta: ChannelDeltaConnection, branchDelta: ChannelDeltaConnection) {
		channelDelta.on("process", (msg) => {
			branchDelta.processMessages({
				envelope: msg.envelope,
				local: false,
				messagesContent: msg.messagesContent.map((mc) => ({
					...mc,
					localOpMetadata: undefined,
				})),
			});
		});

		branchDelta.on("submit", (content, branchMetadata) => {
			this.branchPending.push({ content, branchMetadata, branchDelta, channelDelta });
		});
	}
	merge() {
		// validate main channel isn't dirty before merging for now
		// we need to ensure we are on the same remote op, and there are no
		// local ops, or they are accounted for.
		const pending = this.branchPending.splice(0);
		pending.forEach((p) => {
			p.branchDelta.reSubmit(p.content, p.branchMetadata);
		});
		const rebased = this.branchPending.splice(0);
		rebased.forEach((p) => {
			const channelMetadata = p.channelDelta.applyStashedOp(p.content);
			p.channelDelta.submit(p.content, channelMetadata);
		});
	}
}
